### ISSUE TITLE
Not sure as to why I am getting this error

### ISSUE THREAD

**Issue by RohanRadia** [WatchBeam/implicit-oauth-example#5]
### https://gyazo.com/623eb66ee03b6c061a4e0297317a8735

https://mixer.com/oauth/authorize?response_type=token&scope=interactive:robot:self&client_id=9ab6ccdd2bb3a8fe1db5f8f549652b23e7467022c06736fb&redirect_uri=https:%2F%2Fgoogle.com

**Comment by ProbablePrime** [comment]
This usually happens when your OAuth configuration doesnt include the redirect uri you've specified. As you most likely don't own google.com this is why its not working.

Try double checking within your OAuth Menu that you have a host specified in your host list and that it is the host being used in your OAuth request.
